### PR TITLE
Add background highlight on lines that are added or deleted

### PR DESCRIPTION
**Pull request by yudai-nkt**
ToDo:

- [ ] Span the background highlight over the whole line

### CODE REVIEW

**Comment by yudai-nkt** [comment]
@botatooo Glad if you're interested in this PR and would give some feedback!

**Comment by adntaha** [comment]
it's great!!!

Edit: now that I have a bit more time, I don't know astro but this seems like a reliable way to do it :D

**Comment by yudai-nkt** [comment]
Thanks! I'll try to address the remaining ToDo above. I'm terrible at CSS, so there might be a chance that it's not implemented before merging though.

**Comment by yudai-nkt** [comment]
I noticed that GitHub's diff syntax highlight (not the diff UI) doesn't highlight the whole line like in honojs/hono#837. So I reverted [6b803d8](https://github.com/yudai-nkt/workers-types-diff/pull/3/commits/6b803d855ab10be94ef9c7bf63e02ba6cbceef08) and merge this PR as is.

**Pull request merged**
